# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 16:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0020_userrecipientidentifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipientidentifier',
            old_name='format',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='userrecipientidentifier',
            unique_together=set([('user', 'type', 'identifier')]),
        ),
    ]
