# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 21:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badgeuser', '0022_auto_20190405_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgrAccessToken',
        ),
    ]
