# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0044_auto_20180713_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='expires_in_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
