# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 21:21


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0046_auto_20181114_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeinstance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
