# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 19:29


from django.db import migrations

def nullify_blanks(apps, schema_editor):
    Issuer = apps.get_model('issuer', 'Issuer')
    Issuer.objects.filter(source_url='').update(source_url=None)

class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0047_badgeinstance_user'),
    ]

    operations = [
        migrations.RunPython(nullify_blanks),
    ]
