# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 19:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0048_auto_20190812_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='source_url',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]