# Generated by Django 2.2.13 on 2020-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0053_auto_20200608_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeinstance',
            name='revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
