FROM nginx:latest

COPY .docker/etc/nginx.conf /etc/nginx/nginx.conf
COPY .docker/etc/site.conf /etc/nginx/sites-available/

RUN mkdir -p /etc/nginx/sites-enabled/\
    && ln -s /etc/nginx/sites-available/site.conf /etc/nginx/sites-enabled/

CMD ["nginx", "-g", "daemon off;"]