FROM python:3.7-slim

RUN mkdir /badgr_server
WORKDIR /badgr_server

COPY manage.py                     /badgr_server
COPY .docker/etc/uwsgi.ini         /badgr_server
COPY .docker/etc/wsgi.py           /badgr_server
COPY apps                          /badgr_server/apps
COPY .docker/etc/settings_local.py /badgr_server/apps/mainsite/

RUN pip install uwsgi
