FROM python:3.7-slim

RUN mkdir /badgr_server
WORKDIR /badgr_server

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y default-libmysqlclient-dev \
                       python3-dev \
                       python3-cairo \
                       build-essential \
                       xmlsec1

RUN pip install uwsgi

COPY requirements.txt              /badgr_server
RUN pip install -r requirements.txt
