# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 23:03


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saml2Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saml2Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_conf_url', models.URLField(help_text=b'The URL for the XML configuration for SAML2 flows. Get this from the Identity Provider Application.', verbose_name=b'Metadata Configuration URL')),
                ('slug', models.CharField(help_text=b'This slug must be prefixed with saml2.', max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='saml2account',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badgrsocialauth.Saml2Configuration'),
        ),
        migrations.AddField(
            model_name='saml2account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
