# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 15:05


from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ('mainsite', '0018_auto_20190723_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesstokenscope',
            unique_together=set([('token', 'scope')]),
        ),
    ]
