# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-31 01:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_auto_20191114_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgrapp',
            name='ui_login_redirect',
            field=models.URLField(null=True),
        ),
    ]
