# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-06 22:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_auto_20191230_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgrapp',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
