# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_applicationinfo_badge_connect'),
        ('mainsite', '0022_badgrapp_is_default'),
    ]

    operations = [
    ]
