# Generated by Django 2.1.15 on 2020-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_merge_20200211_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
