# Generated by Django 2.1.15 on 2020-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0012_auto_20200106_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpackbadgeshare',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=254),
        ),
        migrations.AlterField(
            model_name='backpackcollectionshare',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=254),
        ),
    ]
